name: numeric_utils_example
description: Demonstrates usage of the numeric_utils Dart library.
version: 0.1.0
publish_to: none

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  numeric_utils:
    path: ../
  decimal: ^3.2.1
  rational: ^2.0.0
  intl: ^0.20.2
